export const TOGGLE_FOO  = "TOGGLE_FOO";

export const SET_ACTIVE_DONATION  = "SET_ACTIVE_DONATION";

export const CALL_FETCH_DONATIONS = "CALL_FETCH_DONATIONS";
export const FETCH_DONATIONS_SUCC = "FETCH_DONATIONS_SUCC";
export const FETCH_DONATIONS_FAIL = "FETCH_DONATIONS_FAIL";
