export const TOGGLE_FOO  = "TOGGLE_FOO";

export const SET_ACTIVE_DONATION  = "SET_ACTIVE_DONATION";

export const NEW_DONATION_POST = "NEW_DONATION_POST";
export const NEW_DONATION_SUCC = "NEW_DONATION_SUCC";
export const NEW_DONATION_FAIL = "NEW_DONATION_FAIL";

export const CLAIM_DONATION_PART  = "CLAIM_DONATION_PART";
export const CLAIM_DONATION_SUCC  = "CLAIM_DONATION_SUCC";
export const CLAIM_DONATION_FAIL  = "CLAIM_DONATION_FAIL";

export const CALL_FETCH_DONATIONS = "CALL_FETCH_DONATIONS";
export const FETCH_DONATIONS_SUCC = "FETCH_DONATIONS_SUCC";
export const FETCH_DONATIONS_FAIL = "FETCH_DONATIONS_FAIL";
